export type LeadRow = {
  id: string;
  contact_id: string | null;
  name: string;
  phone: string | null;
  phone_normalized: string | null;
  email: string | null;
  locality: string | null;
  contacted_at: string;
  reception: string | null;
  contact_medium: string | null;
  lead_source: string | null;
  project: string | null;
  status: string;
  broker_name: string | null;
  broker_email: string | null;
  derived_at: string | null;
  accepted_at: string | null;
  followup_3d: string | null;
  feedback: string | null;
  feedback_at: string | null;
  request_summary: string | null;
  interest: string | null;
  progress: string | null;
  is_duplicate: boolean;
  data_source: string | null;
  month: string | null;
  created_at: string;
  updated_at: string;
};
